### ISSUE TITLE
Accordion size broken in Firefox

### ISSUE THREAD

**Issue by raphielscape** [hentaiOS-Infrastructure/wiki.helluvaos.com#13]
This is a sub-tracker of https://github.com/hentaiOS-Infrastructure/wiki-frontpage-develop/issues/8 regarding Browser-specific breakage

This issue reproducible with Firefox 90 Upwards in our Development Environment

![Screenshot 2021-10-08 at 19-37-42 Hello from hentaiOS Docuwiki hentaiOS Docuwiki](https://user-images.githubusercontent.com/23637682/136558371-ef1839de-71e9-42c1-95e3-de3ae45ba622.png)

**Comment by fdemb** [comment]
https://github.com/hentaiOS-Infrastructure/wiki-frontpage-develop/pull/16
