### ISSUE TITLE
The accordion is broken - fix asap

### ISSUE THREAD

**Issue by Hasaber8** [hentaiOS-Infrastructure/wiki.helluvaos.com#8]
1. Accordion stays in the light theme when the whole page is in the dark theme. 
2. Font family is different from the web page.
Including mock-up for reference.
![image](https://user-images.githubusercontent.com/43720061/134797193-ece3c961-79eb-4029-a792-942be59ffbd2.png)
![image](https://user-images.githubusercontent.com/43720061/134797196-0c77288f-6a34-4bb7-a1ba-bcd6fbb93bd4.png)

**Comment by raphielscape** [comment]
Reopening this issue tracker because of tracked breakage and design inconsistencies.
